CREATE TABLE IF NOT EXISTS users (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '用户ID',
    email VARCHAR(255) NOT NULL COMMENT '邮箱（登录账号，唯一）',
    password_hash VARCHAR(255) NOT NULL DEFAULT '' COMMENT '密码哈希（bcrypt加密）',
    nickname VARCHAR(100) NULL DEFAULT NULL COMMENT '昵称',
    name VARCHAR(50) NULL DEFAULT NULL COMMENT '姓名',
    phone VARCHAR(20) NULL DEFAULT NULL COMMENT '手机号',
    birth_date DATE NULL DEFAULT NULL COMMENT '出生日期',
    education VARCHAR(50) NULL DEFAULT NULL COMMENT '最高学历（如：本科、硕士、博士）',
    work_years TINYINT UNSIGNED NULL DEFAULT NULL COMMENT '工作年限',
    city VARCHAR(50) NULL DEFAULT NULL COMMENT '所在城市',
    status TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '账号状态：0-禁用，1-正常',
    last_login_at DATETIME NULL DEFAULT NULL COMMENT '最后登录时间',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_email (email),
    KEY idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户表';

CREATE TABLE IF NOT EXISTS resumes (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '简历ID',
    user_id BIGINT UNSIGNED NOT NULL COMMENT '用户ID',
    title VARCHAR(255) NOT NULL DEFAULT '未命名简历' COMMENT '简历标题',
    version INT UNSIGNED NOT NULL DEFAULT 1 COMMENT '版本号',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id),
    KEY idx_user_id (user_id),
    CONSTRAINT fk_resumes_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='简历主表';

CREATE TABLE IF NOT EXISTS resume_details (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '明细ID',
    resume_id BIGINT UNSIGNED NOT NULL COMMENT '简历ID',
    section_type VARCHAR(32) NOT NULL COMMENT '分段类型：EDUCATION/WORK_EXPERIENCE/PROJECT/SKILL/SUMMARY',
    section_name VARCHAR(64) NOT NULL COMMENT '分段标题',
    content TEXT NOT NULL COMMENT '分段内容（JSON格式）',
    sort_order INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '排序序号',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id),
    KEY idx_resume_id (resume_id),
    CONSTRAINT fk_details_resume FOREIGN KEY (resume_id) REFERENCES resumes(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='简历明细表';

CREATE TABLE IF NOT EXISTS resume_files (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '文件ID',
    user_id BIGINT UNSIGNED NOT NULL COMMENT '用户ID',
    resume_id BIGINT UNSIGNED NULL COMMENT '关联简历ID',
    file_type VARCHAR(32) NOT NULL COMMENT '文件类型：JPG/PNG/PDF/DOCX',
    file_path VARCHAR(512) NOT NULL COMMENT '文件存储路径',
    file_size BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '文件大小（字节）',
    original_name VARCHAR(255) NOT NULL COMMENT '原始文件名',
    ocr_text TEXT NULL COMMENT 'OCR识别结果',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    PRIMARY KEY (id),
    KEY idx_user_id (user_id),
    KEY idx_resume_id (resume_id),
    CONSTRAINT fk_files_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_files_resume FOREIGN KEY (resume_id) REFERENCES resumes(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='简历文件表';
