ALTER TABLE users
    MODIFY COLUMN email VARCHAR(255) NOT NULL,
    ADD COLUMN nickname VARCHAR(100) NULL DEFAULT NULL AFTER password_hash,
    ADD COLUMN name VARCHAR(50) NULL DEFAULT NULL AFTER nickname,
    ADD COLUMN phone VARCHAR(20) NULL DEFAULT NULL AFTER name,
    ADD COLUMN birth_date DATE NULL DEFAULT NULL AFTER phone,
    ADD COLUMN education VARCHAR(50) NULL DEFAULT NULL AFTER birth_date,
    ADD COLUMN work_years TINYINT UNSIGNED NULL DEFAULT NULL AFTER education,
    ADD COLUMN city VARCHAR(50) NULL DEFAULT NULL AFTER work_years,
    ADD COLUMN status TINYINT UNSIGNED NOT NULL DEFAULT 1 AFTER city,
    ADD COLUMN last_login_at DATETIME NULL DEFAULT NULL AFTER status,
    ADD COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER created_at;

UPDATE users SET nickname = username WHERE nickname IS NULL AND username IS NOT NULL AND username != '';

ALTER TABLE users DROP INDEX username;
ALTER TABLE users DROP COLUMN username;

ALTER TABLE users ADD UNIQUE KEY uk_email (email);
ALTER TABLE users ADD KEY idx_status (status);
